### ISSUE TITLE
tcl version requirement broken since eggdrop 1.9.4rc1

### ISSUE THREAD

**Issue by michaelortmann** [eggheads/eggdrop#1403]
eggdrop should require at least tcl 8.3, see: https://github.com/eggheads/eggdrop/blob/2a6a36888f5aa2204d84a9e6282d35e5421c2c8a/aclocal.m4#L1097

but current eggdrop 2a6a36888f5aa2204d84a9e6282d35e5421c2c8a (20221230) is broken for tcl 8.3 and 8.4:
```
LD_LIBRARY_PATH=/home/michael/opt/tcl-8.4.1/lib ./configure --with-tcllib=/home/michael/opt/tcl-8.4.1/lib/libtcl8.4.so --with-tclinc=/home/michael/opt/tcl-8.4.1/include/tcl.h
LD_LIBRARY_PATH=/home/michael/opt/tcl-8.4.1/lib make config
LD_LIBRARY_PATH=/home/michael/opt/tcl-8.4.1/lib make
[...]
gcc -fPIC -g -O2 -pipe -Wall -I. -I../../.. -I../../.. -I../../../src/mod  -DHAVE_CONFIG_H -I/home/michael/opt/tcl-8.4.1/include -g3 -DDEBUG -DDEBUG_ASSERT -DDEBUG_MEM -DDEBUG_DNS  -DMAKING_MODS -c .././server.mod/server.c && mv -f server.o ../
In file included from .././server.mod/server.c:144:
.././server.mod/servmsg.c: In function ‘encode_msgtags’:
.././server.mod/servmsg.c:316:3: error: unknown type name ‘Tcl_DictSearch’; did you mean ‘Tcl_HashSearch’?
  316 |   Tcl_DictSearch s;
      |   ^~~~~~~~~~~~~~
      |   Tcl_HashSearch
```

broken since #1320

**Comment by thommey** [comment]
I think we should raise our minimum requirement to 8.5 as Eggdrop in its current state makes heavy use of dictionary for the CAP API. Emulating that would require parsing flat key/value lists which is possible but I believe unnecessary effort to support ancient systems that don't upgrade to 1.9 anyway.
