### ISSUE TITLE
eggdrop 1.9.2 don't compile on OpenBSD 7.0

### ISSUE THREAD

**Issue by carlin0** [eggheads/eggdrop#1269]
`make

Making core eggdrop files...

cc -g -O2 -pipe -Wall -I.. -I..  -DHAVE_CONFIG_H -I/usr/local/include/tcl8.5  -c bg.c
In file included from bg.c:25:
In file included from ./main.h:90:
./eggdrop.h:791:3: error: unknown type name 'pthread_mutex_t'
  pthread_mutex_t mutex;
  ^
1 error generated.
*** Error 1 in src (Makefile:83 'bg.o')
`

**Comment by vanosg** [comment]
Thanks... sorry we missed that! You can try ./configure --disable-tdns  and then compile from there, does that remedy the issue for you?

**Comment by carlin0** [comment]
> Thanks... sorry we missed that! You can try ./configure --disable-tdns and then compile from there, does that remedy the issue for you?

great! this solves
