### ISSUE TITLE
Error: conflicting types for 'socklen_t' when cross-compiling

### ISSUE THREAD

**Issue by eelcohn** [eggheads/eggdrop#247]
Hi,

When I cross-compile Eggdrop 1.8.0RC1 I get an error:

`eggdrop.h:272: error: conflicting types for 'socklen_t'`
`/home/......../powerpc-none-linux-gnuspe/bin/../lib/gcc/powerpc-none-linux-gnuspe/4.3.2/../../../../powerpc-none-linux-gnuspe/include/unistd.h:245: error: previous declaration of 'socklen_t' was here`

This issue can be resolved by # (remarking) out the socklen_t definition in eggdrop.h:
`// typedef int socklen_t;`

It's a kinda ugly hack though. Maybe this could be added to eggdrop.h?
`#ifndef HAVE_SOCKLEN_T`
`#ifndef socklen_t`
`typedef int socklen_t;`
`#endif`
`#endif`

This issue has been present in the 1.6.x branch of Eggdrop as well.

PS Great work on the 1.8.x release of Eggdrop! Keep it up!

**Comment by vanosg** [comment]
eelcohuininga, thanks so much for the bug report and kind words- we'll take a look at this and see what we can do. Thanks!
