### ISSUE TITLE
./configure --disable-tls broken

### ISSUE THREAD

**Issue by michaelortmann** [eggheads/eggdrop#1271]
its broken by the following 2 independent bugs / commits:

```
$ ./configure --disable-tls
[...]
gcc -g -O2 -pipe -Wall -I.. -I..  -DHAVE_CONFIG_H -I/usr/include -g3 -DDEBUG -DDEBUG_ASSERT -DDEBUG_MEM -DDEBUG_DNS  -c botcmd.c
botcmd.c: In function ‘bot_nlinked’:
botcmd.c:726:53: error: ‘struct dcc_t’ has no member named ‘ssl’
  726 |   addbot(newbot, dcc[idx].nick, next, x, i, dcc[idx].ssl);
      |                                                     ^
make[1]: *** [Makefile:83: botcmd.o] Error 1
make[1]: Leaving directory '/home/michael/projects/eggdrop5/eggdrop/src'
make: *** [Makefile:251: debug] Error 2
```

broken since commit b8250a56b801ee7c1dd9f5d041f2c94d664958ab

```
gcc -fPIC -g -O2 -pipe -Wall -I. -I../../.. -I../../.. -I../../../src/mod  -DHAVE_CONFIG_H -I/usr/include -g3 -DDEBUG -DDEBUG_ASSERT -DDEBUG_MEM -DDEBUG_DNS  -DMAKING_MODS -c .././server.mod/server.c && mv -f server.o ../
In file included from .././server.mod/server.c:154:
.././server.mod/tclserv.c: In function ‘tcl_server’:
.././server.mod/tclserv.c:534:38: error: ‘struct server_list’ has no member named ‘ssl’
  534 |       snprintf(s, sizeof s, "%s%d", z->ssl ? "+" : "", z->port);
      |                                      ^~

```

broken since commit 881f5ee158c84926c85e1d01f73d3e466a79a73f
